group=io.arconia.migrations
version=1.0.1-SNAPSHOT

org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true

org.gradle.jvmargs=-Xmx6g

assertjVersion=3.27.7
jSpecifyVersion=1.0.0
jUnitVersion=6.1.2
logbackVersion=1.6.0
mockitoVersion=5.23.0
openRewriteVersion=3.35.0
slf4jVersion=2.0.18
