name: "Report: Bug"
description: "Create a bug report."
title: "BUG TITLE"
labels: [bug, triage]
body:
- type: "markdown"
  attributes:
    value: |
      Welcome to Arconia Migrations! Please replace the **`BUG TITLE`** template above with a short title summarizing what the bug entails.
      ---
- type: "input"
  id: "arconia-migrations-version"
  attributes:
    label: "Arconia Migrations version"
    description: "The Arconia Migrations version you are using."
  validations:
    required: true
- type: "textarea"
  id: "what-happened"
  attributes:
    label: "What happened"
    description: "A small description of the issue."
  validations:
    required: true
- type: "textarea"
  id: "what-expected"
  attributes:
    label: "What did you expect"
    description: "A description of what was expected."
  validations:
    required: true
- type: "textarea"
  id: "what-steps-taken"
  attributes:
    label: "What steps did you take"
    description: "A clear and concise description steps that can be used to reproduce the problem."
  validations:
    required: true
- type: "textarea"
  id: "logs"
  attributes:
    label: "Relevant log output"
    description: "Please paste any relevant log output or stack traces. This will be automatically formatted as code."
    render: "shell"
  validations:
    required: false
- type: "textarea"
  id: "additional-context"
  attributes:
    label: "Anything else you would like to add"
    description: "Additional information that will assist in solving the issue."
  validations:
    required: false
- type: "checkboxes"
  id: "sanity-check"
  attributes:
    label: "I assert that this issue is relevant for Arconia Migrations"
    options:
      - label: "I assert that this is a bug and not a support request. If you need assistance, please use [GitHub Discussions](https://github.com/arconia-io/arconia-migrations/discussions)."
        required: true
      - label: "I assert that this is not a [duplicate of an existing issue](https://github.com/arconia-io/arconia-migrations/issues). "
        required: true
      - label: "I assert that I have read the [Arconia Code of Conduct](https://github.com/arconia-io/arconia-migrations/blob/main/CODE_OF_CONDUCT.md) and agree to abide by it."
        required: true
- type: "markdown"
  attributes:
    value: |
      Thank you for helping improve Arconia Migrations!
      ---
