= Spring Cloud 2025.1
:description: Migrate your Spring application to the latest Spring Cloud 2025.1.x release.
:cli-command: arconia rewrite run --recipe-name io.arconia.rewrite.spring.cloud2025.UpgradeSpringCloud_2025_1
:recipe-id: io.arconia.rewrite.spring.cloud2025.UpgradeSpringCloud_2025_1
:rewrite-module: rewrite-spring

When upgrading to Spring Cloud 2025.1, refer to the https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2025.1-Release-Notes[Spring Cloud 2025.1 Release Notes] to find out about newly introduced APIs, deprecated APIs, and information about breaking changes.

The `{recipe-id}` recipe automates most of the changes introduced in Spring Cloud 2025.1. You can use it to update your project to the latest Spring Cloud 2025.1.x release.

The recipe will:

* Upgrade `org.springframework.cloud:spring-cloud-dependencies` to the 2025.1.x release line.
* Upgrade all other `org.springframework.cloud` dependencies to the 5.0.x release line.
* Rename Spring Cloud configuration properties to match the new property names.

See its xref:recipe-catalog/rewrite-spring.adoc#io_arconia_rewrite_spring_cloud2025_UpgradeSpringCloud_2025_1[entry in the Recipe Catalog] for the full list of recipes this upgrade applies, each with its options and a before/after example.

== Run the recipe

include::partial$run-recipe.adoc[]
