plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

ext {
    set("cycloneDxVersion", '3.4.1')
    set("errorPronePluginVersion", '5.1.0')
    set("nullAwayPluginVersion", '3.1.0')
    set("openRewriteBuildVersion", '2.21.1')
}

dependencies {
    implementation "net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin:${errorPronePluginVersion}"
    implementation "net.ltgt.nullaway:net.ltgt.nullaway.gradle.plugin:${nullAwayPluginVersion}"
    implementation "org.cyclonedx:cyclonedx-gradle-plugin:${cycloneDxVersion}"
    implementation "org.openrewrite.build.recipe-library-base:org.openrewrite.build.recipe-library-base.gradle.plugin:${openRewriteBuildVersion}"
}
